#!/bin/bash
# ============================================================================
# Fnos PXE Server - Entrypoint Script
# ============================================================================
# This script is called when the container starts.
# It handles:
#   1. Environment variable validation
#   2. ISO extraction (if ISO exists in /iso)
#   3. DHCP, TFTP, NFS service configuration
#   4. Service startup
# ============================================================================

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

echo ""
echo "=============================================="
echo "  Fnos PXE Server v1.0"
echo "=============================================="
echo ""

# ============================================================================
# 1. 显示默认配置
# ============================================================================
log_info "默认配置:"
echo "  服务器 IP:  ${SERVER_IP:-192.168.8.4}"
echo "  子网掩码:   ${SUBNET_MASK:-255.255.255.0}"
echo "  DHCP 范围:  ${DHCP_RANGE_START:-192.168.8.100} - ${DHCP_RANGE_END:-192.168.8.200}"
echo "  TFTP 目录:  /tftpboot"
echo "  NFS 目录:   /nfsroot"
echo ""

# ============================================================================
# 2. 检查 ISO 文件
# ============================================================================
ISO_DIR="/iso"
TFTPBOOT="/tftpboot"
NFSROOT="/nfsroot"

# 检查 ISO 目录
if [ -d "$ISO_DIR" ]; then
    ISO_FILES=$(find "$ISO_DIR" -maxdepth 1 -name "*.iso" -type f 2>/dev/null)
    if [ -n "$ISO_FILES" ]; then
        log_info "发现 ISO 文件:"
        for iso in $ISO_FILES; do
            ISO_SIZE=$(du -h "$iso" | cut -f1)
            log_info "  - $(basename $iso) ($ISO_SIZE)"
        done
        echo ""
        log_info "正在提取 ISO boot 文件..."
        /scripts/extract-iso.sh
    else
        log_warn "ISO 目录为空: $ISO_DIR"
        log_warn "请将 Fnos ISO 文件放入 $ISO_DIR 并重启容器"
    fi
else
    log_warn "ISO 目录不存在: $ISO_DIR"
fi

# ============================================================================
# 3. 配置 DHCP Server
# ============================================================================
log_info "配置 DHCP Server..."

# 生成 DHCP 配置文件
DHCP_CONFIG="/etc/dhcp/dhcpd.conf"
cat > "$DHCP_CONFIG" << 'EOF'
# DHCP Server Configuration for Fnos PXE Boot
# Generated by entrypoint.sh

# Global settings
authoritative;
ddns-update-style none;
default-lease-time 600;
max-lease-time 7200;

# Log to stdout for Docker logs
log-facility local7;

# Subnet configuration
subnet ${SUBNET_NETWORK} netmask ${SUBNET_MASK} {
EOF

# 如果有 boot 文件名，添加 PXE 选项
if [ -n "$BOOT_FILE" ]; then
    cat >> "$DHCP_CONFIG" << EOF
    # PXE Boot Configuration
    range ${DHCP_RANGE_START} ${DHCP_RANGE_END};
    option routers ${SERVER_IP};
    option subnet-mask ${SUBNET_MASK};
    option domain-name-servers ${SERVER_IP};
    
    # PXE-specific options
    option广播-address ${SUBNET_BROADCAST};
    
    # Boot file name (relative to TFTP root)
    filename "${BOOT_FILE}";
    
    next-server ${SERVER_IP};
}
EOF
else
    cat >> "$DHCP_CONFIG" << EOF
    # DHCP only (no PXE)
    range ${DHCP_RANGE_START} ${DHCP_RANGE_END};
    option routers ${SERVER_IP};
    option subnet-mask ${SUBNET_MASK};
    option domain-name-servers ${SERVER_IP};
    option broadcast-address ${SUBNET_BROADCAST};
}
EOF
fi

log_success "DHCP 配置完成"

# ============================================================================
# 4. 配置 NFS
# ============================================================================
log_info "配置 NFS..."

# 更新 exports 文件
cat > /etc/exports << EOF
/nfsroot          *(ro,sync,no_subtree_check,no_root_squash,async,insecure)
EOF

log_success "NFS 配置完成"

# ============================================================================
# 5. 启动服务
# ============================================================================
log_info "启动服务..."
echo ""

# 启动 rpcbind (NFS 需要)
log_info "启动 rpcbind..."
rpcbind || true

# 启动 NFS
log_info "启动 NFS Server..."
exportfs -ra
rpc.nfsd 8
rpc.mountd

# 启动 xinetd (TFTP)
log_info "启动 TFTP Server (xinetd)..."
xinetd -dontfork &

# 等待一下让 xinetd 启动
sleep 2

# 启动 DHCP
log_info "启动 DHCP Server..."
touch /var/lib/dhcp/dhcpd.leases
chmod 644 /var/lib/dhcp/dhcpd.leases 2>/dev/null || true
dhcpd -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd || true

echo ""
echo "=============================================="
log_success "所有服务已启动!"
echo "=============================================="
echo ""
log_info "服务状态:"
echo "  DHCP Server:  UDP:67"
echo "  TFTP Server:  UDP:69"
echo "  NFS Server:   TCP:2049"
echo "  Mountd:       TCP:20048"
echo ""
log_info "PXE 客户端可以开始网络启动了!"
echo ""

# ============================================================================
# 6. 显示 TFTP/NFS 目录内容
# ============================================================================
if [ -d "$TFTPBOOT" ] && [ "$(ls -A $TFTPBOOT 2>/dev/null)" ]; then
    log_info "TFTP 目录内容 (/tftpboot):"
    find "$TFTPBOOT" -type f -exec ls -lh {} \; 2>/dev/null | awk '{print "    " $9 " (" $5 ")"}' | sed "s|$TFTPBOOT/||g"
    echo ""
fi

if [ -d "$NFSROOT" ] && [ "$(ls -A $NFSROOT 2>/dev/null)" ]; then
    log_info "NFS 目录内容 (/nfsroot):"
    find "$NFSROOT" -maxdepth 2 -type d 2>/dev/null | head -10 | sed "s|$NFSROOT|    |g"
    echo ""
fi

# ============================================================================
# 7. 保持容器运行
# ============================================================================
log_info "保持容器运行 (tail -f /dev/null)..."
echo ""
tail -f /dev/null
